### ISSUE TITLE
Script is not exiting with the same status code as xcodebuild

### ISSUE THREAD

**Issue by supermarin** [ciryon/OCUnit2JUnit#19]
Say you've run `xcodebuild` and it exited with 65, but it didn't output  that explicitly.

After piping, exit status is 0, even tho xcodebuild failed.

**Comment by mykoma** [comment]
> Id recommend using pipefail or pipestatus to properly detect the XCode exit status. pipefail will set the exit status $? to the exit code of the last program to exit non-zero (or zero if all exited successfully).
> 
> set -o pipefail
> xcodebuild .... 2>&1 | ocunit2junit
> 
> Great explanation of options here: http://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another/73180#73180

@darend You save me. Thanks.

**Comment by supermarin** [comment]
wow, completely forgot I've opened this issue... in 2013!
@darend thank you so much for the link, you thought me a new thing at the time and helped make `xcpretty` a thing.
